### PR TITLE
Add setup.py console script entry point

### PR DESCRIPTION
**Pull request by peterk87**
## Description of changes

- copied [upload_run.py](https://github.com/phac-nml/irida-uploader/blob/development/upload_run.py) to `iridauploader/core/cli.py` with slight refactoring (argparse calls in module scope into `init_argparser` function called in `main` function) 
- added console script entry point to `setup.py` so that irida-uploader can be installed with `pip`
- tested by installing `irida-uploader` into virtualenv using pip (`$ python -m venv venv && source venv/bin/activate && pip install -e . && irida-uploader --help`)

## Related issue

- #84

## Checklist
Things for the developer to confirm they've done before the PR should be accepted:

* [ ] CHANGELOG.md updated with information for new change.
* [ ] Tests added (or description of how to test) for any new features.
* [ ] User documentation updated for UI or technical changes.

### CODE REVIEW

**Comment by JeffreyThiessen** [comment]
This is a great first cut of something I've been wanting to fix for a while.

The main issue that will need to be looked at is making sure that this will also work with the pynsist windows builds. Those builds were the reason I had split the files into upload_run.py and upload_gui.py in the first place, but I would like to get all that cleaned up into one place.

Before the next release full release I'd like get this or a similar change included but I'll need to spend some time figuring out how we can also clean up the gui launching code (possibly similar to this code change, and move the launch code somewhere into `iridauploader/gui/`), and have it work nicely with the windows installers. I have a feeling we may also want to drop the `.sh` files that start the uploader as well since installing with pip will be much cleaner.

**Comment by peterk87** [comment]
Thanks @JeffreyThiessen. It's great that the command-line version is easily installed with Conda. It makes it very convenient for uploading multiple samples at once. I can only imagine the challenges with making the uploader tool work under both Windows and Linux. Hope this helps!

**Comment by JeffreyThiessen** [comment]
@peterk87 I pulled your code into a new branch to use as the starting point for changing how the builds work in the uploader. I'm going to close this PR since I'll just be building off the new branch/PR.

https://github.com/phac-nml/irida-uploader/pull/93

Feel free to test it out while it's still in the work in progress state, and thanks again for getting the ball rolling on this.

**Comment by peterk87** [comment]
Sounds great @JeffreyThiessen! I'm glad I could help out a little. It looks like there are a lot of good changes coming down the pipe.

**Pull request closed without merging**
