### PR TITLE
Check that base_url ends with /api/

### PR DESCRIPTION
**Pull request by pvanheus**
## Description of changes
A simple check that base_url ends with /api/

## Related issue
No issue, but I made this mistake with the configuration so thought a check might be useful to others.

## Checklist
Things for the developer to confirm they've done before the PR should be accepted:

* [x] CHANGELOG.md updated with information for new change.
* [ ] Tests added (or description of how to test) for any new features.
* [ ] User documentation updated for UI or technical changes.

### CODE REVIEW

**Comment by JeffreyThiessen** [comment]
I think this is a good idea to add. Could you update to development and put the changelog line under the 0.6.0 changes and I'll merge it in.

**Comment by pvanheus** [comment]
> I think this is a good idea to add. Could you update to development and put the changelog line under the 0.6.0 changes and I'll merge it in.

I've updated as requested and moved the CHANGELOG.md line to the 0.6.0 section

**Comment by pvanheus** [comment]
@JeffreyThiessen can you look at this CI failure? I don't quite understand why this change would break an integration test.

**Comment by JeffreyThiessen** [comment]
> @JeffreyThiessen can you look at this CI failure? I don't quite understand why this change would break an integration test.

Yeah we noticed this happening yesterday too. Something to do with mvn repos / spring pom files being fetched from the wrong url. I'm sure your code changes are good to go, but we are currently just waiting to see if whoever goofed up their repo's upstream from us will fix them.

**Review by JeffreyThiessen — APPROVED** [review]
PR is good to go, waiting on upstream repo issues to resolve.

**Pull request merged**
