### PR TITLE
fix miniseq parser crashing when trying to read a miseq run

### PR DESCRIPTION
**Pull request by JeffreyThiessen**
## Description of changes
fix miniseq parser crashing when trying to read a miseq run

## Related issue
N/A

## Checklist
Things for the developer to confirm they've done before the PR should be accepted:

* [x] CHANGELOG.md updated with information for new change.
* [ ] Tests added (or description of how to test) for any new features.
* [ ] User documentation updated for UI or technical changes.

### CODE REVIEW

**Comment by joshsadam** [comment]
@JeffreyThiessen can you check your tests on this.

**Comment by JeffreyThiessen** [comment]
> @JeffreyThiessen can you check your tests on this.

Selenium is failing some tests randomly, I'll hit merge once it passes.

**Comment by joshsadam** [comment]
Please do not merge your own PRs.  Just let me know when they pass.

**Comment by JeffreyThiessen** [comment]
> Please do not merge your own PRs. Just let me know when they pass.

Passed now.

**Pull request merged**
