### PR TITLE
Add entry_points entry to setup.py

### PR DESCRIPTION
**Pull request by dfornika**
## Description of changes
Add entry to `setup.py` that creates an `irida-uploader` command-line executable when installing via `pip`

## Checklist
Things for the developer to confirm they've done before the PR should be accepted:

* [ ] CHANGELOG.md updated with information for new change.
* [ ] Tests added (or description of how to test) for any new features.
* [ ] User documentation updated for UI or technical changes.

### CODE REVIEW

**Comment by dfornika** [comment]
Build error seems unrelated to the change in this pull-request. In the `integrationtestsdev` test suite:

```
Traceback (most recent call last):
  File "start_integration_tests.py", line 28, in <module>
    main()
  File "start_integration_tests.py", line 24, in main
    tests_integration.start(args.branch)
  File "/home/travis/build/phac-nml/irida-uploader/iridauploader/tests_integration/tests_integration.py", line 94, in start
    setup_handler = start_setup(branch)
  File "/home/travis/build/phac-nml/irida-uploader/iridauploader/tests_integration/tests_integration.py", line 60, in start_setup
    client_id, client_secret, password = data_setup(setup)
  File "/home/travis/build/phac-nml/irida-uploader/iridauploader/tests_integration/tests_integration.py", line 36, in data_setup
    setup.login()
  File "/home/travis/build/phac-nml/irida-uploader/iridauploader/tests_integration/integration_data_setup.py", line 126, in login
    self.driver.find_element_by_id("emailTF").clear()
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="emailTF"]"}
  (Session info: headless chrome=81.0.4044.113)
Makefile:66: recipe for target 'integrationtestsdev' failed
make: *** [integrationtestsdev] Error 1
The command "make $TEST_SUITE" exited with 2.
```

**Comment by JeffreyThiessen** [comment]
> Build error seems unrelated to the change in this pull-request. In the `integrationtestsdev` test suite:

Yep, I was looking at that issue already, I think something in the irida dev branch changed.

I think I'll merge this this change in for the 0.5.0 release, we have some more stuff coming for cloud deployment that we want on PyPi so it will be good to include there.

**Comment by JeffreyThiessen** [comment]
How did you run the code with this change?
I built a wheel and installed it to a new venv but it did not start when running the `irida-uploader` command.

```
(test_venv) jthiessen@computer:~/git/test_venvs$ irida-uploader --help
Traceback (most recent call last):
  File "/home/jthiessen/git/test_venvs/test_venv/bin/irida-uploader", line 7, in <module>
    from upload_run import main
ModuleNotFoundError: No module named 'upload_run'
```

The generated /bin/irida-uploader file looks like this

```
#!/home/jthiessen/git/test_venvs/test_venv/bin/python3

# -*- coding: utf-8 -*-
import re
import sys

from upload_run import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

**Comment by dfornika** [comment]
This is how I tested it out:

- Created a new conda environment with just python included and activate it:

```
conda create -n irida-uploader-dev python
conda activate irida-uploader-dev
```

Then use pip to install into the conda:

```
pip install -e .
```

The `-e` flag installs in 'editable' mode, so if changes are made to the source code they're automatically installed into the environment. (That probably wasn't necessary here because I didn't change any actual source but that's what I did.)

I got a similar `irida-uploader` script. But when I tried running `irida-uploader -h`, I got the expected help text.

Would it make sense to move the `upload_run.py` script into the `iridauploader` package? Or I think I've seen other libraries that have a `scripts` directory that can be referred to in `setup.py`.

**Comment by dfornika** [comment]
This is what my `irida-uploader` script looks like:

```python
#!/Users/dfornika/miniconda3/envs/irida-uploader-dev/bin/python3.7
# EASY-INSTALL-ENTRY-SCRIPT: 'iridauploader','console_scripts','irida-uploader'
__requires__ = 'iridauploader'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('iridauploader', 'console_scripts', 'irida-uploader')()
    )
```

**Comment by JeffreyThiessen** [comment]
I am closing this because the changes have effectively been done from the rebuild branch now in dev. The launch scripts work a bit different now and have better compatibility with pypi and hopefully will make the conda build simpler too. It will be released with 0.5.0, hopefully next week.

If you see anything that you think needs changing in how I changed the build scripts, please let me know.

**Pull request closed without merging**
